export const DEFAULT_LOCALE = 'en';
export const CLEAR_ERROR = 'JUMP/App/CLEAR_ERROR';
export const SYSTEM_ERROR = 'JUMP/App/SYSTEM_ERROR';
export const FETCH_DATALIST = 'JUMP/App/FETCH_DATALIST';
export const FETCH_DATALIST_SUCCESS = 'JUMP/App/FETCH_DATALIST_SUCCESS';
export const FETCH_DATALIST_ERROR = 'JUMP/App/FETCH_DATALIST_ERROR';
